### PR TITLE
determinant of nxn matrix

### PR DESCRIPTION
**Pull request by FireNdIce3**

### CODE REVIEW

**Review by sam-tripathi — CHANGES_REQUESTED** [review]
yeah you did a great job 
could you also add questions on the top of each program in form of comments

**Comment by FireNdIce3** [comment]
Okay sure

**Review by FireNdIce3 — COMMENTED** [review]
I have done the changes and also added the two files
Can you please add Hacktoberfest label in this
Thanks

**Review by sam-tripathi — APPROVED** [review]
yes I have reviewed you have neaty done the job great

**Comment by sam-tripathi** [comment]
do follow us for more such repository

**Pull request merged**
