### PR TITLE
Data Structures and Problems in Java

### PR DESCRIPTION
**Pull request by achiverram28**

### CODE REVIEW

**Review by sam-tripathi — CHANGES_REQUESTED** [review]
YOU HAVE DONE A GREAT JOB BRO  BUT FOR A BEGINNER IT IS HARD TO UNDERSTAND YOUR PROGRAM SO COULD YOU ADD COMMENTS ON THE TOP OF EACH PROGRAM ABOUT WHAT IT IS? IN ADDITION TO THIS PLEASE TRY TO ADD COMMENTS IN BETWEEN FOR A BETTER UNDERSTANDING F THE BEGINNERS.

**Comment by achiverram28** [comment]
Ok I will do it

**Comment by achiverram28** [comment]
I have updated the repository , please check and approve it

**Comment by sam-tripathi** [comment]
Impressive work

**Pull request merged**
