### PR TITLE
Add a recursion folder

### PR DESCRIPTION
**Pull request by jainpatel25**
Please check and review it and add a hactoberfest tag

### CODE REVIEW

**Review by sam-tripathi — APPROVED** [review]
wow great work

**Comment by sam-tripathi** [comment]
I am accepting it. nevertheless, if you could add an explanation of recursion, it would be a great help for beginners who will learn using this repo.

**Comment by jainpatel25** [comment]
I will add explanation to recursion
And any more work for me as a hactoberfest tag?

**Comment by sam-tripathi** [comment]
no thanks, nevertheless thanks for asking. I think you should increase your experience  by contributing to various other open-source projects.

**Pull request merged**
